-- ============================================================================
-- Hotel Personalization - Account-Level Setup
-- ============================================================================
-- Creates account-level objects: role, database, warehouse, schemas
-- Requires ACCOUNTADMIN role
-- 
-- Session variables (set by deploy.sh):
--   $FULL_PREFIX, $PROJECT_ROLE, $PROJECT_WH
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- 1. Create Project Role
-- ============================================================================
CREATE ROLE IF NOT EXISTS IDENTIFIER($PROJECT_ROLE)
    COMMENT = 'Primary role for Hotel Personalization project';

-- Grant role to current user
SET MY_USER = (SELECT CURRENT_USER());
GRANT ROLE IDENTIFIER($PROJECT_ROLE) TO USER IDENTIFIER($MY_USER);
GRANT ROLE IDENTIFIER($PROJECT_ROLE) TO ROLE SYSADMIN;

-- ============================================================================
-- 2. Create Database
-- ============================================================================
CREATE DATABASE IF NOT EXISTS IDENTIFIER($FULL_PREFIX)
    COMMENT = 'Hotel Personalization - AI-Powered Guest Experience Platform';

-- ============================================================================
-- 3. Create Schemas (Medallion Architecture)
-- ============================================================================
SET FQ_BRONZE = $FULL_PREFIX || '.BRONZE';
SET FQ_SILVER = $FULL_PREFIX || '.SILVER';
SET FQ_GOLD = $FULL_PREFIX || '.GOLD';
SET FQ_BUSINESS_VIEWS = $FULL_PREFIX || '.BUSINESS_VIEWS';
SET FQ_SEMANTIC_VIEWS = $FULL_PREFIX || '.SEMANTIC_VIEWS';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($FQ_BRONZE)
    COMMENT = 'Bronze layer - Raw data ingestion (PMS, bookings, amenities, usage)';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($FQ_SILVER)
    COMMENT = 'Silver layer - Cleaned and standardized data with enrichment';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($FQ_GOLD)
    COMMENT = 'Gold layer - Analytics-ready aggregations with ML scoring';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($FQ_BUSINESS_VIEWS)
    COMMENT = 'Business views for operational reporting and dashboards';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($FQ_SEMANTIC_VIEWS)
    COMMENT = 'Semantic views for natural language queries via Snowflake Intelligence';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($FULL_PREFIX || '.STREAMLIT')
    COMMENT = 'Streamlit applications for interactive dashboards';

-- ============================================================================
-- 4. Create Warehouse
-- ============================================================================
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($PROJECT_WH)
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Hotel Personalization queries and data processing';

-- ============================================================================
-- 5. Create Additional Project Roles (Optional - for advanced RBAC)
-- ============================================================================
-- These roles provide fine-grained access control for different teams

-- Set role name variables
SET ROLE_ADMIN = $PROJECT_ROLE || '_ADMIN';
SET ROLE_GUEST_ANALYST = $PROJECT_ROLE || '_GUEST_ANALYST';
SET ROLE_REVENUE_ANALYST = $PROJECT_ROLE || '_REVENUE_ANALYST';
SET ROLE_EXPERIENCE_ANALYST = $PROJECT_ROLE || '_EXPERIENCE_ANALYST';
SET ROLE_DATA_ENGINEER = $PROJECT_ROLE || '_DATA_ENGINEER';

-- Administrative role with full access
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_ADMIN)
    COMMENT = 'Administrative role for hotel personalization project management';

-- Analyst roles for different aspects of hotel operations
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_GUEST_ANALYST)
    COMMENT = 'Analyst role for guest behavior and preference analysis';

CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_REVENUE_ANALYST)
    COMMENT = 'Analyst role for revenue optimization and pricing strategies';

CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_EXPERIENCE_ANALYST)
    COMMENT = 'Analyst role for guest experience and satisfaction analysis';

CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_DATA_ENGINEER)
    COMMENT = 'Data engineer role for data pipeline management';

-- ============================================================================
-- 6. Grant Ownership and Permissions
-- ============================================================================

-- Grant ownership of database to project role
GRANT OWNERSHIP ON DATABASE IDENTIFIER($FULL_PREFIX) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;

-- Grant ownership of all schemas
GRANT OWNERSHIP ON SCHEMA IDENTIFIER($FQ_BRONZE) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA IDENTIFIER($FQ_SILVER) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA IDENTIFIER($FQ_GOLD) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA IDENTIFIER($FQ_BUSINESS_VIEWS) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA IDENTIFIER($FQ_SEMANTIC_VIEWS) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;

-- Grant ownership of warehouse
GRANT OWNERSHIP ON WAREHOUSE IDENTIFIER($PROJECT_WH) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;

-- Grant admin role to main project role
GRANT ROLE IDENTIFIER($ROLE_ADMIN) TO ROLE IDENTIFIER($PROJECT_ROLE);
GRANT ROLE IDENTIFIER($ROLE_GUEST_ANALYST) TO ROLE IDENTIFIER($PROJECT_ROLE);
GRANT ROLE IDENTIFIER($ROLE_REVENUE_ANALYST) TO ROLE IDENTIFIER($PROJECT_ROLE);
GRANT ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST) TO ROLE IDENTIFIER($PROJECT_ROLE);
GRANT ROLE IDENTIFIER($ROLE_DATA_ENGINEER) TO ROLE IDENTIFIER($PROJECT_ROLE);

-- Grant database usage to analyst roles
GRANT USAGE ON DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_ADMIN);
GRANT USAGE ON DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_GUEST_ANALYST);
GRANT USAGE ON DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_REVENUE_ANALYST);
GRANT USAGE ON DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST);
GRANT USAGE ON DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_DATA_ENGINEER);

-- Grant warehouse usage to analyst roles
GRANT USAGE ON WAREHOUSE IDENTIFIER($PROJECT_WH) TO ROLE IDENTIFIER($ROLE_ADMIN);
GRANT USAGE ON WAREHOUSE IDENTIFIER($PROJECT_WH) TO ROLE IDENTIFIER($ROLE_GUEST_ANALYST);
GRANT USAGE ON WAREHOUSE IDENTIFIER($PROJECT_WH) TO ROLE IDENTIFIER($ROLE_REVENUE_ANALYST);
GRANT USAGE ON WAREHOUSE IDENTIFIER($PROJECT_WH) TO ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST);
GRANT USAGE ON WAREHOUSE IDENTIFIER($PROJECT_WH) TO ROLE IDENTIFIER($ROLE_DATA_ENGINEER);

-- Grant schema usage to all roles
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_ADMIN);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_GUEST_ANALYST);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_REVENUE_ANALYST);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_DATA_ENGINEER);

-- Grant table and view permissions
GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_GUEST_ANALYST);
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_GUEST_ANALYST);

GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_REVENUE_ANALYST);
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_REVENUE_ANALYST);

GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST);
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST);

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_DATA_ENGINEER);
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_DATA_ENGINEER);

-- Grant future object permissions
GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_GUEST_ANALYST);
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_GUEST_ANALYST);

GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_REVENUE_ANALYST);
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_REVENUE_ANALYST);

GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST);
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_EXPERIENCE_ANALYST);

GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_DATA_ENGINEER);
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE IDENTIFIER($FULL_PREFIX) TO ROLE IDENTIFIER($ROLE_DATA_ENGINEER);

-- ============================================================================
-- 7. Summary
-- ============================================================================
SELECT 'Account-level setup completed successfully!' AS STATUS;
SELECT 
    $PROJECT_ROLE AS ROLE_CREATED,
    $FULL_PREFIX AS DATABASE_CREATED,
    $PROJECT_WH AS WAREHOUSE_CREATED,
    'BRONZE, SILVER, GOLD, BUSINESS_VIEWS, SEMANTIC_VIEWS' AS SCHEMAS_CREATED;

